swagger: '2.0'
info:
  description: API of the Sport App
  version: 1.0.0
  title: Sport Event App

tags:
- name: user
  description: Endpoints connected to User
- name: event
  description: Endpoints connected to Event
- name: sport
  description: Endpoints connected to Sport

paths:

  /api/user/register:
    post:
      tags:
      - user
      description: |
        Registers a new User on the website
      consumes:
      - application/json
      parameters:
      - in: body
        name: newUser
        schema:
          type: object
          properties:
            userName:
              type: string
            email:
              type: string
            fullName:
              type: string
            password:
              type: string
      responses:
        201:
          description: User registered successfully
        400:
          description: Invalid or missing information
        409:
          description: User already registered
        500:
          description: Server error

  /api/user/login:
    post:
      tags:
      - user
      description: |
        A User can login, if correct credentials are provided.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: user
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
      responses:
        200:
          description: Correct credentials, login successful
          headers:
            x-auth-token:
              type: string
          schema:
            $ref: '#/definitions/User'
        400:
          description: No or invalid credentials provided

  /api/user/me:
    get:
      tags:
      - user
      operationId: getCurrentUser
      description: |
        Gets the current logged in User
      produces:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      responses:
        200:
          description: Valid token provided
          schema:
            $ref: '#/definitions/User'
        401:
          description: Unauthorized
  
  /api/user/update:
    put:
      tags:
      - user
      description: |
        Updates the User's data. Only provide fields, which has to be updated ( currentPassword is always required )
      consumes:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      - in: body
        name: updateUser
        schema:
          type: object
          properties:
            newFullName:
              type: string
            newIntroduction:
              type: string
            newPassword:
              type: string
            currentPassword:
              type: string
      responses:
        201:
          description: Successfully updated
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server Error
  
  /api/user/search:
    get:
      tags:
      - user
      operationId: searchUser
      description: |
        Can search in users
      produces:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      - name: q
        in: query
        type: string
        default: empty
        description: Keyword, cann occur in userName or fullName
      - name: orderBy
        in: query
        type: string
        enum: [ userName, fullName ]
        default: userName
      - name: pageSize
        in: query
        type: number
        minimum: 1
        maximum: 100
        default: 10
      - name: page
        in: query
        type: number
        minimum: 1
        default: 1
      
      responses:
        200:
          description: Search results
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '#/definitions/User'
              totalResults:
                type: number
              totalPages:
                type: number
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server Error
  
  /api/user/findByUserName/{userName}:
    get:
      tags:
      - user
      description: |
        Finds the User with given username
      produces:
      - application/json
      parameters:
      - name: userName
        in: path
        required: true
        type: string
      responses:
        200:
          description: User found
          schema:
            type: object
            properties:
              userName:
                type: string
              fullName:
                type: string
              introduction:
                type: string
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server Error
  
  /api/sports:
    get:
      tags:
      - sport
      operationId: getSports
      description: |
        Returns the currently supported sport list
      produces:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      responses:
        200:
          description: List of all sports
          schema:
            type: array
            items:
              $ref: '#/definitions/Sport'
        401:
          description: Unauthorized
        500:
          description: Server error
  
  /api/event/search:
    get:
      tags:
      - event
      operationId: searchEvent
      description: |
        Can search in the current events
      produces:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      - name: userName
        in: query
        type: string
        default: empty
        description: Shows only events the user participates on
      - name: sport
        in: query
        type: string
        default: all
      - name: dateFrom
        in: query
        type: string
        format: date-time
        default: current time
      - name: dateTo
        in: query
        type: string
        format: date-time
        default: empty
      - name: lat
        in: query
        type: number
      - name: long
        in: query
        type: number
      - name: orderBy
        in: query
        type: string
        enum: [ date, deadline, name, location, distance ]
        default: date
      - name: pageSize
        in: query
        type: number
        minimum: 1
        maximum: 100
        default: 10
      - name: page
        in: query
        type: number
        minimum: 1
        default: 1
      
      responses:
        200:
          description: Search results
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: '#/definitions/Event'
              totalResults:
                type: number
              totalPages:
                type: number
              latitude:
                type: number
              longitude:
                type: number
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server Error
  
  /api/event/{id}:
    get:
      tags:
      - event
      description: | 
        Gets an event by it's id
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: number
      responses:
        200:
          description: Result
          schema:
            $ref: '#/definitions/Event'
        400:
          description: ID not found
        401:
          description: Unauthorized
        500:
          description: Server Error
  
  /api/event/new:
    post:
      tags:
      - event
      description: |
        Registers a new Event
      consumes:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      - in: body
        name: newEvent
        schema:
          type: object
          properties:
            sport:
              type: string
            name:
              type: string
            latitude:
              type: number
              minimum: -90
              maximum: 90
            longitude:
              type: number
              minimum: -180
              maximum: 180
            location:
              type: string
            date:
              type: string
              format: date-time
            deadline:
              type: string
              format: date-time
            description:
              type: string
              
      responses:
        201:
          description: Event registered successfully
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server error

  /api/event/apply:
    post:
      tags:
      - event
      description: |
        Applies a new team for event
      consumes:
      - application/json
      parameters:
      - in: header
        name: x-auth-token
        type: string
        required: true
      - in: body
        name: applyEvent
        schema:
          type: object
          properties:
            eventID:
              type: number
            teamName:
              type: string
            members:
              type: array
              items:
                type: string
      responses:
        201:
          description: Applied successfully
        400:
          description: Invalid or missing information
        401:
          description: Unauthorized
        500:
          description: Server error
  
  /api/event/old:
    delete:
      tags:
      - event
      description: |
        Deletes every expired events from database. Admin access level required.
      responses:
        200:
          description: Deleted
        401:
          description: Unauthorized
        403:
          description: Access denied
        500:
          description: Server error

definitions:
  User:
    type: object
    properties:
      userName:
        type: string
      fullName:
        type: string
  
  Sport:
    type: object
    properties:
      name:
        type: string
      minPlayers:
        type: integer
      maxPlayers:
        type: integer
  
  Event:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      creator:
        type: string
      sport:
        type: string
      minTeamSize:
        type: number
      maxTeamSize:
        type: number
      latitude:
        type: number
      longitude:
        type: number
      location:
        type: string
      distance:
        type: number
        description: can be null
      date:
        type: string
        format: date-time
      deadline:
        type: string
        format: date-time
      description:
        type: string

schemes:
 - https
# host: sport-temalabor.azurewebsites.net
# Added by API Auto Mocking Plugin
# host: sport-temalabor.azurewebsites.net
basePath: /temalaborsport/sportAPI/1.0.0
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
